---
# tasks file for ovirt-sdk
- name: 'Install oVirt 4 repositories'
  package:
    name: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm'
    state: present
  notify:
    - "Clean {{ ansible_distribution }} cache packages"

- meta: flush_handlers

- block:
    - name: 'Install requirements CentOS'
      package:
        name: "{{ CentOS.packages }}"
        state: present

    - name: 'Install Pushbullet library'
      easy_install:
        name: 'pushbullet.py'
        state: present

  when: "'CentOS' in ansible_distribution"

- block:
    - name: 'Install requirements Fedora'
      package:
        name: "{{ Fedora.packages }}"
        state: present

    - name: 'Install oVirt SDK Fedora'
      pip:
        name: "{{ Fedora.pip }}"
        state: present
        extra_args: --user
        executable: pip3
      environment:
        PYCURL_SSL_LIBRARY: 'openssl'

  when: "'Fedora' in ansible_distribution"

- name: 'Generate dummy SSH key'
  command: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""'
  args:
    creates: '/root/.ssh/id_rsa'

- name: 'Set Git config to work locally'
  git_config:
    name: http.sslVerify
    value: false

- name: 'Update Ansible.cfg'
  ini_file:
    path: '/etc/ansible/ansible.cfg'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'defaults', option: 'host_key_checking', value: 'False' }
    - { section: 'defaults', option: 'jinja2_extensions', value: 'jinja2.ext.do' }
