---
# tasks file for ovirt-sdk
- name: 'Install requirements Fedora'
  package:
    name: "{{ item }}"
    state: present
  with_items: [ 'docker', 'etcd', 'python-requests', 'python2-docker', 'python3-docker', 'python-click', 'bind-utils', 'mlocate', 'git', 'wget', 'patch', 'vim' ]
  when: "'Fedora' in ansible_distribution"

- name: 'Install requirements CentOS'
  package:
    name: "{{ item }}"
    state: present
  with_items: [ 'docker', 'etcd', 'python-requests', 'docker-python', 'python-click', 'bind-utils', 'mlocate', 'git', 'wget', 'patch', 'vim' ]
  when: "'CentOS' in ansible_distribution"

- name: 'Install oVirt 4 repositories'
  package:
    name: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm'
    state: present
  when: "'CentOS' in ansible_distribution"

- name: 'Install oVirt SDK'
  pip:
    name: 'ovirt-engine-sdk-python'
    state: present
    extra_args: --user
  when: "'Fedora' in ansible_distribution"

- name: 'Install oVirt SDK'
  yum:
    name: 'python-ovirt-engine-sdk4'
    state: present
    update_cache: true
  when: "'CentOS' in ansible_distribution"

- name: 'Install Pushbullet library'
  easy_install:
    name: 'pushbullet.py'
    state: present

- name: 'Generate dummy SSH key'
  command: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""'
  args:
    creates: '/root/.ssh/id_rsa'

- name: 'Set Git config to work locally'
  git_config:
    name: http.sslVerify
    value: false

- name: 'Update Ansible.cfg'
  ini_file:
    path: '/etc/ansible/ansible.cfg'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'defaults', option: 'host_key_checking', value: 'False' }
    - { section: 'defaults', option: 'jinja2_extensions', value: 'jinja2.ext.do' }
